global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "golang-api"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          group: "production"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
